### ISSUE TITLE
Prerelease dependencies is adding extra pre release tag new nuspec

### ISSUE THREAD

**Issue by ashishdawale20** [avrum/NuspecAutoUpdate#5]
Let say I have package.config with 
`<package id="Test" version="1.0.7201-dev" targetFramework="net461" />`

And nuspect with:
`<dependency id="Test" version="[1.0.7201-dev]" />
`
On building the project my nuspec getting changed to below with extra "-dev"

`<dependency id="TestFramework.Common" version="**[1.0.7201-dev-dev]**" />`

**Comment by avrum** [comment]
Can you elaborate?
I'm not following the issue...

**Comment by ashishdawale20** [comment]
@avrum  - My bad
XML input was not visible in my first comments. I have edited it now.

**Comment by avrum** [comment]
Ammm haven't heard about this "dev" addition to versions.
Are the nuget officially support this attribute for version?
Can you add a link that document that? I'll merge if it's officially support it :)

**Comment by ashishdawale20** [comment]
@avrum 
Please have a look at this: 
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

**Comment by avrum** [comment]
@ashishdawale20 that's great,
Thanks for the reference,
I'll merge your request

**Comment by avrum** [comment]
Merged

**Comment by avrum** [comment]
Please add yourself in the readme file to as a contributer, and ill merge it too
